name: serdes_json_generator
description: code generator for serdes_json
version: 0.3.2
homepage: https://github.com/sysint64/serdes_json

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^3.2.0
  build: ^2.0.0
  source_gen: ^1.0.0
  source_helper: ^1.3.1
  equatable: ^2.0.0
  recase: ^4.0.0
  collection: ^1.15.0
  # serdes_json: ^0.2.0
  serdes_json:
    path: ../serdes_json

dev_dependencies:
  flutter_test:
    sdk: flutter
